name: object-calisthenics

services:
  app:
    container_name: $COMPOSE_PROJECT_NAME-dev-php-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: "7.4-fpm-alpine3.16"
        PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
        USER_NAME: "${USER:-www-data}"
    ports:
      - 8086:80
      - 443:443
    volumes:
      - ./:/var/www/${COMPOSE_PROJECT_NAME}
